=== tgiroux/ISIS3/isis/src/docsys/Schemas/Documentation/documentation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Stuart C Sides (USGS) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:annotation>
		<xs:documentation>Isis Documentation Schema</xs:documentation>
	</xs:annotation>
	<xs:annotation>
		<xs:documentation>XML schema for describing the documentation available on the Isis web site </xs:documentation>
	</xs:annotation>
	<xs:annotation>
		<xs:documentation>Designed by Deborah Lee Soltesz, dsoltesz@usgs.gov, 10/11/2002, USGS Astrogeology Research Program, Flagstaff, AZ</xs:documentation>
	</xs:annotation>
	<xs:element name="documentation">
		<xs:annotation>
			<xs:documentation>container describing a single electronic document. "hidden" attribute should prevent this document from being linked in an autogenerated TOC.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="files"/>
				<xs:element ref="category"/>
				<xs:element ref="audience"/>
				<xs:element ref="bibliography"/>
				<xs:element ref="history" minOccurs="0"/>
			</xs:all>
			<xs:attribute name="hidden" type="xs:boolean" use="optional" default="false"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="categoryType" final="restriction">
		<xs:annotation>
			<xs:documentation>enumeration for categories the document should be filed under</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="hidden">
				<xs:annotation>
					<xs:documentation>marks the document as "hidden", thus should not be linked to or otherwise referenced publicly</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="about">
				<xs:annotation>
					<xs:documentation>a document that gives general information about the software system and developers - history, policies, contact information, etc.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="guide">
				<xs:annotation>
					<xs:documentation>a document that serves as a guide (how-to or tutorial) for using the software or API, modifying the software, etc.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="tutorial">
				<xs:annotation>
					<xs:documentation>a document that serves as a tutorial on some subject regarding using, programming, maintaining, etc. Isis</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="installation">
				<xs:annotation>
					<xs:documentation>a document that provides information about the installation of the software</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="administration">
				<xs:annotation>
					<xs:documentation>document that gives information about maintaining the software installation</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="technicaldoc">
				<xs:annotation>
					<xs:documentation>a document that contains highly technical information about the software</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="support">
				<xs:annotation>
					<xs:documentation>document related to support of the software by the software developers (i.e. USGS Isis Programming Team)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="information">
				<xs:annotation>
					<xs:documentation>a document that serves simply to provide information</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="reference">
				<xs:annotation>
					<xs:documentation>a document that serves as a reference (as opposed to a guide/how-to/tutorial)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="policy">
				<xs:annotation>
					<xs:documentation>a document outlining a policy</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="xml">
				<xs:annotation>
					<xs:documentation>a document about the Isis XML languages</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="api">
				<xs:annotation>
					<xs:documentation>a document about the Isis API</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="isis2">
				<xs:annotation>
					<xs:documentation>a document about the previous version of Isis, Isis 2.1</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="audienceType" final="restriction">
		<xs:annotation>
			<xs:documentation>enumeration for target audience types</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="user">
				<xs:annotation>
					<xs:documentation>A basic user, generally one who does not install, maintain, or program for the software system, but simply uses the software</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="intermediate"/>
			<xs:enumeration value="advanced">
				<xs:annotation>
					<xs:documentation>An advanced user</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="administrator">
				<xs:annotation>
					<xs:documentation>A person who installs and maintains the software package (generally a systems administrator)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="developer">
				<xs:annotation>
					<xs:documentation>A programmer who uses the API to develop applications</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="programmer">
				<xs:annotation>
					<xs:documentation>A programmer who modifies the software system (Isis), i.e. develops Objects</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="all">
				<xs:annotation>
					<xs:documentation>all audiences</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="files">
		<xs:annotation>
			<xs:documentation>list of files that represent this document - for example, if the document is avaible in Word, PDF, and HTML, there would be three files listed here, one for each format</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="file" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="category">
		<xs:annotation>
			<xs:documentation>list of categories this document should be linked under</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="categoryItem" type="categoryType" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>a single category in the list (enumerated type)</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="audience">
		<xs:annotation>
			<xs:documentation>list of target audience types</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="target" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="bibliography">
		<xs:annotation>
			<xs:documentation>bibliographic information about the document</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="title"/>
				<xs:element ref="brief"/>
				<xs:element ref="description"/>
				<xs:element ref="author"/>
				<xs:element ref="publisher" minOccurs="0"/>
				<xs:element ref="date"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="history">
		<xs:annotation>
			<xs:documentation>list of history of changes to the document</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="change" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="file">
		<xs:annotation>
			<xs:documentation>container of link (and potentially content) information for files representing the document. "hidden" attribute should prevent this file/subdocument from being linked. "primary" attribute should make this the favored file out of a selection of multiple files. </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="type"/>
				<xs:element ref="size" minOccurs="0"/>
				<xs:element ref="source"/>
				<xs:element ref="subtitle" minOccurs="0"/>
				<xs:element ref="body" minOccurs="0"/>
			</xs:all>
			<xs:attribute name="hidden" type="xs:boolean" use="optional" default="false"/>
			<xs:attribute name="primary" type="xs:boolean" use="optional" default="false"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="type">
		<xs:annotation>
			<xs:documentation>name of the format or other descriptor for this file</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="size">
		<xs:annotation>
			<xs:documentation>size of the file if applicable (ie. not HTML or text)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="source">
		<xs:annotation>
			<xs:documentation>electronic source information</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice>
				<xs:element ref="URL"/>
				<xs:element ref="filename"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="URL">
		<xs:annotation>
			<xs:documentation>full URL to a document at another location</xs:documentation>
		</xs:annotation>
		<xs:complexType/>
	</xs:element>
	<xs:element name="filename">
		<xs:annotation>
			<xs:documentation>filename of document in this document structure (including desired name for HTML output of this document)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="subtitle">
		<xs:annotation>
			<xs:documentation>subtitle (useful for multipage documents)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="body">
		<xs:annotation>
			<xs:documentation>inline document content- this file will be generated as an HTML document. Body must contain either a URI to an external XML file (with root element BODY) or the HTML formatted content</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:choice>
				<xs:any namespace="##any" processContents="skip" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>XML-legal HTML formatted document text</xs:documentation>
					</xs:annotation>
				</xs:any>
				<xs:element ref="src"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="src">
		<xs:annotation>
			<xs:documentation>filename for external XML source of content. External file must have a root element BODY that contains HTML formatted content</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="target" type="audienceType">
		<xs:annotation>
			<xs:documentation>a single target audience type: user, advanced, administrator, developer, programmer</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="title">
		<xs:annotation>
			<xs:documentation>title of the document</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="brief">
		<xs:annotation>
			<xs:documentation>brief description of this document</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="description">
		<xs:annotation>
			<xs:documentation>long description of this document</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="author">
		<xs:annotation>
			<xs:documentation>author's name</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="publisher">
		<xs:annotation>
			<xs:documentation>publisher's information</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="date" type="xs:date">
		<xs:annotation>
			<xs:documentation>date of publication</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="change">
		<xs:annotation>
			<xs:documentation>single history entry</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="date" type="xs:date" use="required"/>
			<xs:attribute name="hidden" use="optional" default="false">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="yes"/>
						<xs:enumeration value="no"/>
						<xs:enumeration value="true"/>
						<xs:enumeration value="false"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== tgiroux/ISIS3/isis/src/docsys/documents/HowToGeneralDocumentation/assets/examples/example2/example2.xml
<?xml version="1.0" encoding="UTF-8"?>
<documentation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://isis.astrogeology.usgs.gov/Schemas/Documentation/documentation.xsd">
  <files>
    <file>
      <body>
        <src>example2_body.xml</src>
      </body>
      <type>HTML</type>
      <source>
        <filename>example2.html</filename>
      </source>
    </file>
  </files>
  <category>
    <categoryItem>about</categoryItem>
  </category>
  <audience>
    <target>all</target>
  </audience>
  <bibliography>
    <title>HTML with External Content Document Example</title>
    <brief>Example of a Document with an external source of body content</brief>
    <description>Example of a Document XML metadata file with the body stored in an external file that will be converted to an HTML file</description>
    <author>Deborah Lee Soltesz</author>
    <date>2002-12-05</date>
  </bibliography>
</documentation>

=== tgiroux/ISIS3/isis/src/docsys/documents/HowToGeneralDocumentation/assets/examples/example4/example4.xml
<?xml version="1.0" encoding="UTF-8"?>
<documentation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://isis.astrogeology.usgs.gov/Schemas/Documentation/documentation.xsd">
  <files>
    <file>
      <type>PNG</type>
      <source>
        <filename>diagram.png</filename>
      </source>
      <size>30 KB</size>
    </file>
  </files>
  <category>
    <categoryItem>guide</categoryItem>
  </category>
  <audience>
    <target>programmer</target>
    <target>developer</target>
  </audience>
  <bibliography>
    <title>Example of an external Document</title>
    <brief>Example of a Document that is a stand-alone external file</brief>
    <description>Example of a Document that is a stand-alone external file. In this case, the file is an image
                        (actually, the Isis Documentation XML Language Diagram),
                        but could be a PDF file, a spreadsheet, or just about anything.
    </description>
    <author>Deborah Lee Soltesz</author>
    <date>2003-01-30</date>
  </bibliography>
</documentation>
